apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictRegistry
metadata:
  name: restrict-registry
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    registry: "docker.io/"
